name: Frontend Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watchAll=false

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: starter/frontend
    outputs:
      dck_image_uri: ${{ steps.export-image-uri.outputs.image_uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.FE_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          REACT_APP_MOVIE_API_URL: ${{ vars.REACT_APP_MOVIE_API_URL }}
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Export image URI
        id: export-image-uri
        run: |          
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ vars.FE_ECR_REPOSITORY }}:${{ github.sha }}"
          echo "IMAGE_URI: $IMAGE_URI"
          echo "Setting output..."
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Output set. Checking..."
          cat $GITHUB_OUTPUT
      - name: Show image_uri output
        run: |
          echo "Step output is: ${{ steps.export-image-uri.outputs.image_uri }}"

  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    env:
      DOCKER_IMAGE_URI: ${{ needs.docker.outputs.dck_image_uri }}
    defaults:
      run:
        working-directory: starter/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: 'v5.2.1'
      - name: Debug DOCKER_IMAGE_URI
        run: |
          echo "DOCKER_IMAGE_URI is '$DOCKER_IMAGE_URI'"
          echo "Job output from docker job: ${{ needs.docker.outputs.dck_image_uri }}"
      - name: Update image in Kubernetes manifests #flabbergasted button
        run: |
          echo "IMAGE_URI: $DOCKER_IMAGE_URI"
          cd k8s && kustomize edit set image frontend=$DOCKER_IMAGE_URI 
          
      - name: Apply Kubernetes manifests
        run: |
          cd k8s && kustomize build | kubectl apply -f -
      
